-- Esquema de Don Parqueo para PostgreSQL (Supabase, Render, local).
-- Ejecútelo conectado a la base que le entregó el proveedor.
-- Equivale a schema-cloud.sql de la versión Node.js/MySQL:
--   ENUM -> VARCHAR + CHECK, LONGBLOB -> BYTEA, DATETIME -> TIMESTAMP,
--   AUTO_INCREMENT -> GENERATED BY DEFAULT AS IDENTITY.
-- Las fechas se guardan en UTC, sin zona horaria.

CREATE TABLE empresas (
    id_empresa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    nit VARCHAR(20) NOT NULL UNIQUE,
    direccion VARCHAR(200),
    telefono VARCHAR(20),
    email VARCHAR(100),
    logo_url BYTEA,
    qr_pago BYTEA,
    activa BOOLEAN DEFAULT TRUE,
    fecha_registro TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    fecha_vencimiento TIMESTAMP,
    plan VARCHAR(20) NOT NULL CHECK (plan IN ('basico', 'premium', 'enterprise'))
);

CREATE TABLE usuarios (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    nombre VARCHAR(100) NOT NULL,
    usuario_login VARCHAR(50) NOT NULL,
    contrasena VARCHAR(255) NOT NULL,
    rol VARCHAR(20) NOT NULL CHECK (rol IN ('admin', 'operador', 'invitado')),
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    ultimo_acceso TIMESTAMP,
    CONSTRAINT uq_usuario_empresa UNIQUE (usuario_login, id_empresa)
);

CREATE TABLE login_attempts (
    id_intento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    usuario_login VARCHAR(50) NOT NULL,
    exitoso BOOLEAN NOT NULL,
    ip_address VARCHAR(45) NOT NULL,
    fecha_intento TIMESTAMP NOT NULL
);
CREATE INDEX idx_usuario_login ON login_attempts(usuario_login);
CREATE INDEX idx_ip_address ON login_attempts(ip_address);
CREATE INDEX idx_fecha_intento ON login_attempts(fecha_intento);

CREATE TABLE tipos_vehiculos (
    id_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    nombre VARCHAR(50) NOT NULL,
    codigo VARCHAR(20) NOT NULL,
    activo BOOLEAN DEFAULT TRUE,
    fecha_creacion TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_tipo_empresa UNIQUE (codigo, id_empresa)
);
CREATE INDEX idx_empresa_tipo ON tipos_vehiculos(id_empresa, activo);

CREATE TABLE configuracion_empresa (
    id_configuracion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    capacidad_total_carros INT NOT NULL DEFAULT 50,
    capacidad_total_motos INT NOT NULL DEFAULT 30,
    capacidad_total_bicicletas INT NOT NULL DEFAULT 20,
    horario_apertura TIME DEFAULT '06:00:00',
    horario_cierre TIME DEFAULT '22:00:00',
    iva_porcentaje NUMERIC(5,2) DEFAULT 19.00,
    moneda VARCHAR(10) DEFAULT 'COP',
    zona_horaria VARCHAR(50) DEFAULT 'America/Bogota',
    operacion_24h BOOLEAN DEFAULT FALSE
);

CREATE TABLE capacidades_tipo (
    id_capacidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_tipo INT NOT NULL REFERENCES tipos_vehiculos(id_tipo),
    capacidad_total INT NOT NULL DEFAULT 0,
    CONSTRAINT uq_capacidad_tipo UNIQUE (id_empresa, id_tipo)
);

CREATE TABLE vehiculos (
    id_vehiculo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    placa VARCHAR(10) NOT NULL,
    id_tipo INT NOT NULL REFERENCES tipos_vehiculos(id_tipo),
    color VARCHAR(30) NOT NULL,
    modelo VARCHAR(50),
    fecha_registro TIMESTAMP DEFAULT (now() AT TIME ZONE 'utc'),
    CONSTRAINT uq_placa_empresa UNIQUE (placa, id_empresa)
);

CREATE TABLE tarifas (
    id_tarifa INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_tipo INT NOT NULL REFERENCES tipos_vehiculos(id_tipo),
    valor_hora NUMERIC(10,2) NOT NULL,
    valor_minuto NUMERIC(10,2) NOT NULL,
    valor_dia_completo NUMERIC(10,2) NOT NULL,
    fecha_vigencia_desde TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    fecha_vigencia_hasta TIMESTAMP,
    activa BOOLEAN DEFAULT TRUE,
    modo_cobro VARCHAR(10) NOT NULL DEFAULT 'mixto' CHECK (modo_cobro IN ('minuto','hora','dia','mixto')),
    paso_minutos_a_horas INT NOT NULL DEFAULT 0,
    paso_horas_a_dias INT NOT NULL DEFAULT 0,
    redondeo_horas VARCHAR(10) NOT NULL DEFAULT 'arriba' CHECK (redondeo_horas IN ('arriba','exacto')),
    redondeo_dias VARCHAR(10) NOT NULL DEFAULT 'arriba' CHECK (redondeo_dias IN ('arriba','exacto')),
    CONSTRAINT chk_valores_no_negativos CHECK (
        valor_hora >= 0 AND valor_minuto >= 0 AND valor_dia_completo >= 0
    )
);

CREATE TABLE movimientos (
    id_movimiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_vehiculo INT NOT NULL REFERENCES vehiculos(id_vehiculo),
    fecha_entrada TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    fecha_salida TIMESTAMP,
    id_tarifa INT NOT NULL REFERENCES tarifas(id_tarifa),
    total_a_pagar NUMERIC(10,2),
    id_usuario_entrada INT NOT NULL REFERENCES usuarios(id_usuario),
    id_usuario_salida INT REFERENCES usuarios(id_usuario),
    estado VARCHAR(12) DEFAULT 'activo' CHECK (estado IN ('activo', 'finalizado')),
    CONSTRAINT chk_fechas CHECK (fecha_salida IS NULL OR fecha_salida >= fecha_entrada)
);

CREATE TABLE pagos (
    id_pago INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_movimiento INT NOT NULL REFERENCES movimientos(id_movimiento),
    metodo_pago VARCHAR(15) NOT NULL CHECK (metodo_pago IN ('efectivo', 'tarjeta', 'QR', 'nequi', 'daviplata', 'breb', 'transferencia')),
    monto NUMERIC(10,2) NOT NULL CHECK (monto > 0),
    fecha_pago TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    referencia_pago VARCHAR(100),
    id_usuario INT NOT NULL REFERENCES usuarios(id_usuario)
);

CREATE INDEX idx_empresa_vehiculo ON vehiculos(id_empresa, placa);
CREATE INDEX idx_empresa_movimientos ON movimientos(id_empresa, fecha_entrada);
CREATE INDEX idx_empresa_pagos ON pagos(id_empresa, fecha_pago);

CREATE VIEW v_movimientos_activos AS
SELECT
    m.id_movimiento,
    m.id_empresa,
    v.placa,
    tv.nombre AS tipo,
    tv.codigo AS tipo_codigo,
    m.fecha_entrada,
    LPAD((FLOOR(d.s / 3600))::int::text, 2, '0') || ':' ||
    LPAD((FLOOR(d.s / 60)::int % 60)::text, 2, '0') || ':' ||
    LPAD((FLOOR(d.s)::int % 60)::text, 2, '0') AS tiempo_transcurrido,
    u.nombre AS registrado_por
FROM movimientos m
JOIN vehiculos v ON m.id_vehiculo = v.id_vehiculo
JOIN tipos_vehiculos tv ON v.id_tipo = tv.id_tipo
JOIN usuarios u ON m.id_usuario_entrada = u.id_usuario
CROSS JOIN LATERAL (
    SELECT GREATEST(0, EXTRACT(EPOCH FROM (now() AT TIME ZONE 'utc') - m.fecha_entrada)) AS s
) d
WHERE m.fecha_salida IS NULL;

CREATE VIEW v_ingresos_diarios AS
SELECT
    p.id_empresa,
    p.fecha_pago::date AS fecha,
    p.metodo_pago,
    COUNT(*) AS cantidad_pagos,
    SUM(p.monto) AS total_ingresos
FROM pagos p
GROUP BY p.id_empresa, p.fecha_pago::date, p.metodo_pago;

CREATE TABLE turnos (
    id_turno INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_usuario INT NOT NULL REFERENCES usuarios(id_usuario),
    fecha_apertura TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    base_inicial NUMERIC(12,2) NOT NULL,
    observacion_apertura VARCHAR(255),
    fecha_cierre TIMESTAMP,
    total_efectivo NUMERIC(12,2),
    total_tarjeta NUMERIC(12,2),
    total_qr NUMERIC(12,2),
    total_general NUMERIC(12,2),
    diferencia NUMERIC(12,2),
    observacion_cierre VARCHAR(255),
    estado VARCHAR(10) NOT NULL DEFAULT 'abierto' CHECK (estado IN ('abierto','cerrado'))
);
CREATE INDEX idx_turno_activo ON turnos(id_empresa, id_usuario, estado);

CREATE TABLE mensualidades (
    id_mensualidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_vehiculo INT NOT NULL REFERENCES vehiculos(id_vehiculo),
    titular_nombre VARCHAR(120) NOT NULL,
    titular_documento VARCHAR(40),
    titular_telefono VARCHAR(30),
    titular_email VARCHAR(120),
    valor_mensual NUMERIC(12,2) NOT NULL,
    fecha_inicio DATE NOT NULL,
    fecha_fin DATE,
    auto_renovar BOOLEAN DEFAULT TRUE,
    estado VARCHAR(10) NOT NULL DEFAULT 'activa' CHECK (estado IN ('activa','vencida','cancelada')),
    observaciones VARCHAR(255),
    fecha_creacion TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc')
);
CREATE INDEX idx_mens_emp_veh ON mensualidades(id_empresa, id_vehiculo);
CREATE INDEX idx_mens_estado ON mensualidades(id_empresa, estado);

CREATE TABLE mensualidades_pagos (
    id_pago_mensualidad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa INT NOT NULL REFERENCES empresas(id_empresa),
    id_mensualidad INT NOT NULL REFERENCES mensualidades(id_mensualidad),
    fecha_pago TIMESTAMP NOT NULL DEFAULT (now() AT TIME ZONE 'utc'),
    periodo_desde DATE NOT NULL,
    periodo_hasta DATE NOT NULL,
    metodo_pago VARCHAR(15) NOT NULL DEFAULT 'efectivo' CHECK (metodo_pago IN ('efectivo','tarjeta','QR','transferencia')),
    monto NUMERIC(12,2) NOT NULL,
    referencia_pago VARCHAR(100),
    id_usuario INT NOT NULL REFERENCES usuarios(id_usuario)
);
CREATE INDEX idx_mp_emp_fecha ON mensualidades_pagos(id_empresa, fecha_pago);

-- Datos iniciales: una empresa de ejemplo para desarrollo local.
-- La contraseña del administrador se crea al arrancar desde ADMIN_INICIAL_PASSWORD
-- (ver app/db.py), así ninguna clave queda escrita en el repositorio.
INSERT INTO empresas (nombre, nit, direccion, telefono, email, plan)
VALUES ('Parqueadero Central', '900123456-7', 'Calle Principal #123', '3001234567', 'info@parqueaderocentral.com', 'premium');

INSERT INTO configuracion_empresa (id_empresa, capacidad_total_carros, capacidad_total_motos, capacidad_total_bicicletas)
VALUES (1, 100, 50, 30);

INSERT INTO tipos_vehiculos (id_empresa, nombre, codigo, activo) VALUES
(1, 'Carro', 'carro', TRUE),
(1, 'Moto', 'moto', TRUE),
(1, 'Bicicleta', 'bici', TRUE);

INSERT INTO capacidades_tipo (id_empresa, id_tipo, capacidad_total) VALUES
(1, 1, 100),
(1, 2, 50),
(1, 3, 30);

INSERT INTO tarifas (id_empresa, id_tipo, valor_hora, valor_minuto, valor_dia_completo, activa) VALUES
(1, 1, 6000.00, 120.00, 30000.00, TRUE),
(1, 2, 3000.00, 60.00, 15000.00, TRUE),
(1, 3, 1500.00, 30.00, 8000.00, TRUE);
